### ISSUE TITLE
Use lowlevel messageId

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia-msgport#104]

**Comment by jiguantong** [comment]
https://layerzeroscan.com/111/address/0x701a95707a0290ac8b90b3719e8ee5b210360883/message/183/address/0x45f1a95a4d3f3836523f5c83673c797f4d4d263b/nonce/79316

fromChainId/fromAddress/toChainId/toChainAddress/nonce

**Comment by jiguantong** [comment]
There's no return value in the lowlevel message protocol when sending message. @hujw77

**Comment by hujw77** [comment]
https://github.com/LayerZero-Labs/LayerZero/blob/48c21c3921931798184367fc02d3a8132b041942/contracts/NonceContract.sol#L10
LayerZero expose the outboundNonce, we could fetch nonce after sending lzmsg.
