### ISSUE TITLE
xAccount's challenge feature should be implemented in module.

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-msgport#196]
This file is not related to xAccount, should move to other places.

In future, xAccount's challenge feature should be implemented in module.

_Originally posted by @hackfisher in https://github.com/darwinia-network/darwinia-msgport/pull/191#discussion_r1453142311_

**Comment by hujw77** [comment]
Use Safe Recovery Services:
- https://safe.mirror.xyz/WxKSxD9J1bRI-SDOuDvAAIezwVrvWWkpuwuzcLDPSmk
