### ISSUE TITLE
Why msg.sender is self?

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-msgport#21]
https://github.com/darwinia-network/darwinia-msgport/blob/adaf5efee53d0a6b60817990bc774663a8671230/contracts/docks/CelerDock.sol#L122

**Comment by wuminzhe** [comment]
Celer dock has not been run in testnet. there may be issues.

**Comment by wuminzhe** [comment]
this function is only called by 'recv'.
<img width="754" alt="image" src="https://github.com/darwinia-network/darwinia-msgport/assets/1608576/e090d1cb-7b04-4109-8fd4-6d41c9019e20">
