### ISSUE TITLE
Line address => Line Id ?

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-msgport#27]
1. Once line underlay message protocol changed, line address may change, It will force dAPP user to update their recv trusted line address. 
2. Immutable address may be better, dAPP user might like immutable things.

**Comment by jiguantong** [comment]
> Once line underlay message protocol changed

I think this is a upgrade of the message protocol. After the upgrade, a new line should be added. The dApp needs to decide whether to trust the new message line. We should not make decisions for the dApp.

**Comment by jiguantong** [comment]
Can I close this issue?
