### ISSUE TITLE
Singleton architecture

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-msgport#30]
https://blog.uniswap.org/uniswap-v4
https://github.com/Uniswap/v4-core/blob/571c7941914b1fb05521e31300a0068a4612358b/contracts/PoolManager.sol#L64

```solidity
mapping(LaneId id => Lane.State) public lanes;
```

**Comment by jiguantong** [comment]
If so we need to handle a lot of adaptation logic in msgport.
