### ISSUE TITLE
Msgport offchain API

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia-msgport#66]
https://github.com/darwinia-network/darwinia-msgport/issues/91

1. build params
2. estimate fee

**Comment by wuminzhe** [comment]
Request:
> GET https://ip:port/path?from_chain_id=97&to_chain_id=1287&gas_limit=100000&payload=0x12345678&from_address=0x...&to_address=0x...

Response:
```json
{
    "fee": "1239546427527472"
}
```

**Comment by jiguantong** [comment]
https://github.com/darwinia-network/darwinia-msgport/issues/78
