### ISSUE TITLE
Can we simplify msgport?

### ISSUE THREAD

**Issue by jiguantong** [darwinia-network/darwinia-msgport#80]
Remove the msgport layer when sending a message.
Msgport is only for user to get line address.

For verify
```
getTargetLineAddress(sourceLineAddress);
```

For sending msg
```
msgLine = msgport.getLine(lineCode);
msgLine.sendMsg();
```

**Comment by jiguantong** [comment]
Msgport usecase:
1. Manage version code <> line address
2. Audit msgline code, for dapp verification

**Comment by hujw77** [comment]
1. msgport -> msgline -> msgport
```
msgport.sendMsg();
```
2. split msgport and msgline
```
msgLine = msgport.getLine(lineCode);
msgLine.sendMsg();
```
This two solution both has 2 calls.
For auth check in recv:
1: msgPort && isTrust(msgline)
2: isTrust(msgline)
